"""Update models with timezone-aware timestamps

Revision ID: 644c75cd8946
Revises: dfbcb83ac6be
Create Date: 2025-05-16 14:55:54.891966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644c75cd8946'
down_revision = 'dfbcb83ac6be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('hour_of_day', sa.Integer(), nullable=True),
    sa.Column('crowd_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_visit')
    # ### end Alembic commands ###
